In [1]:
%matplotlib inline

import os

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn import datasets
from sklearn import svm

In [2]:
iris = datasets.load_iris()

In [5]:
type(iris)

sklearn.utils.Bunch

In [6]:
iris.data.shape

(150, 4)

In [7]:
iris.target.shape

(150,)

In [8]:
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.4, random_state=0)

In [71]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [16]:
X_test[0:10]

array([[ 5.8,  2.8,  5.1,  2.4],
       [ 6. ,  2.2,  4. ,  1. ],
       [ 5.5,  4.2,  1.4,  0.2],
       [ 7.3,  2.9,  6.3,  1.8],
       [ 5. ,  3.4,  1.5,  0.2],
       [ 6.3,  3.3,  6. ,  2.5],
       [ 5. ,  3.5,  1.3,  0.3],
       [ 6.7,  3.1,  4.7,  1.5],
       [ 6.8,  2.8,  4.8,  1.4],
       [ 6.1,  2.8,  4. ,  1.3]])

In [18]:
y_train[0:10]

array([1, 0, 2, 1, 1, 1, 1, 2, 0, 0])

In [19]:
len(y_train)

90

In [20]:
len(y_test)

60

In [21]:
y_test[0:10]

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1])

In [22]:
X_train.shape, y_train.shape

((90, 4), (90,))

In [23]:
X_test.shape, y_test.shape

((60, 4), (60,))

In [24]:
clf = svm.SVC(kernel='linear', C=1).fit(X_train, y_train)

In [25]:
clf

SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [26]:
clf.score(X_test, y_test)

0.96666666666666667

In [27]:
from sklearn.model_selection import cross_val_score

In [28]:
clf = svm.SVC(kernel='linear', C=1)

In [29]:
clf

SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [30]:
scores = cross_val_score(clf, iris.data, iris.target, cv=5)

In [31]:
scores

array([ 0.96666667,  1.        ,  0.96666667,  0.96666667,  1.        ])

In [32]:
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Accuracy: 0.98 (+/- 0.03)


In [34]:
from sklearn import metrics

In [35]:
 scores = cross_val_score(clf, iris.data, iris.target, cv=5, scoring='f1_macro')

In [36]:
scores

array([ 0.96658312,  1.        ,  0.96658312,  0.96658312,  1.        ])

In [37]:
from sklearn import preprocessing

In [38]:
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.4, random_state=0)

In [39]:
scaler = preprocessing.StandardScaler().fit(X_train)

In [40]:
scaler

StandardScaler(copy=True, with_mean=True, with_std=True)

In [41]:
X_train_transformed = scaler.transform(X_train)

In [43]:
X_train_transformed[0:10]

array([[ 0.18206758,  0.71103882,  0.45664061,  0.5584109 ],
       [-1.17402201,  0.00522823, -1.10334891, -1.19183221],
       [-0.04394735, -0.93585257,  0.77939706,  0.93346299],
       [-0.26996228, -0.93585257,  0.29526238,  0.1833588 ],
       [-0.26996228, -0.46531217, -0.02749407,  0.1833588 ],
       [-0.38296975, -1.40639297,  0.1876769 ,  0.1833588 ],
       [ 0.29507505, -0.23004197,  0.51043335,  0.30837617],
       [ 1.53815717,  0.24049843,  1.26353174,  0.80844563],
       [-0.60898468,  1.41684942, -1.15714165, -1.19183221],
       [-1.73905934, -0.23004197, -1.37231262, -1.31684958]])

In [44]:
clf = svm.SVC(C=1).fit(X_train_transformed, y_train)

In [62]:
clf

Pipeline(memory=None,
     steps=[('standardscaler', StandardScaler(copy=True, with_mean=True, with_std=True)), ('svc', SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False))])

In [61]:
len(X_train_transformed)

90

In [45]:
X_test_transformed = scaler.transform(X_test)

In [46]:
clf.score(X_test_transformed, y_test)  

0.93333333333333335

In [47]:
from sklearn.pipeline import make_pipeline

In [48]:
clf = make_pipeline(preprocessing.StandardScaler(), svm.SVC(C=1))

In [49]:
clf

Pipeline(memory=None,
     steps=[('standardscaler', StandardScaler(copy=True, with_mean=True, with_std=True)), ('svc', SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False))])

In [51]:
from sklearn.model_selection import ShuffleSplit

In [52]:
n_samples = iris.data.shape[0]

In [53]:
n_samples

150

In [54]:
cv = ShuffleSplit(n_splits=3, test_size=0.3, random_state=0)

In [55]:
cv

ShuffleSplit(n_splits=3, random_state=0, test_size=0.3, train_size=None)

In [56]:
cross_val_score(clf, iris.data, iris.target, cv=cv)

array([ 0.97777778,  0.93333333,  0.95555556])

In [73]:
from sklearn.model_selection import cross_val_predict

In [74]:
predicted = cross_val_predict(clf, iris.data, iris.target, cv=10) 

In [75]:
predicted

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [76]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [77]:
# imports
from sklearn.linear_model import LogisticRegression
from sklearn.cross_validation import (StratifiedKFold, cross_val_score,
                                      train_test_split)
from sklearn import datasets

# setup data
iris = datasets.load_iris()
X = iris.data
y = iris.target

# setup model
cv = StratifiedKFold(y, 10)
logreg = LogisticRegression()

# cross-validation scores
scores = cross_val_score(logreg, X, y, cv=cv)

# predict probabilities
Xtrain, Xtest, ytrain, ytest = train_test_split(X, y)
logreg.fit(Xtrain, ytrain)
proba = logreg.predict_proba(Xtest)

C:\Users\AMAMUN\AppData\Local\conda\conda\envs\PythonData\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [79]:
class proba_logreg(LogisticRegression):
    def predict(self, X):
        return LogisticRegression.predict_proba(self, X)

In [80]:
# cross validation probabilities
probas = cross_val_predict(proba_logreg(), X, y, cv=cv)

In [81]:
probas

array([[  8.78465722e-01,   1.21515959e-01,   1.83194488e-05],
       [  8.06498209e-01,   1.93451531e-01,   5.02597529e-05],
       [  8.51590275e-01,   1.48367737e-01,   4.19879953e-05],
       [  8.21196553e-01,   1.78713883e-01,   8.95631594e-05],
       [  8.92653269e-01,   1.07328048e-01,   1.86830619e-05],
       [  9.31255925e-01,   6.87177803e-02,   2.62945267e-05],
       [  9.02197715e-01,   9.77278240e-02,   7.44606683e-05],
       [  8.65656472e-01,   1.34307478e-01,   3.60495558e-05],
       [  8.08522672e-01,   1.91330017e-01,   1.47311502e-04],
       [  7.96065034e-01,   2.03888493e-01,   4.64733804e-05],
       [  8.88988944e-01,   1.11001618e-01,   9.43743514e-06],
       [  8.60692852e-01,   1.39257396e-01,   4.97523713e-05],
       [  7.90005740e-01,   2.09953563e-01,   4.06970455e-05],
       [  8.33256835e-01,   1.66696591e-01,   4.65741555e-05],
       [  9.24412394e-01,   7.55860463e-02,   1.55924436e-06],
       [  9.66495396e-01,   3.35009375e-02,   3.6669433

In [3]:
from xgboost import XGBClassifier

C:\Users\AMAMUN\AppData\Local\conda\conda\envs\PythonData\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [2]:
from sklearn.datasets import make_hastie_10_2
from sklearn.ensemble import GradientBoostingClassifier

X, y = make_hastie_10_2(random_state=0)
X_train, X_test = X[:2000], X[2000:]
y_train, y_test = y[:2000], y[2000:]

model = GradientBoostingClassifier(n_estimators=100, learning_rate=1.0, max_depth=1, random_state=0).fit(X_train, y_train)
model.score(X_test, y_test)

0.91300000000000003

In [6]:
make_hastie_10_2

<function sklearn.datasets.samples_generator.make_hastie_10_2>

In [7]:
X_train.shape

(2000, 10)